export enum AuthState {
  NOT_INITIALIZED = 'NOT_INITIALIZED',
  INITIALIZING = 'INITIALIZING',
  READY = 'READY',
  LOGGING_IN = 'LOGGING_IN',
  AUTHENTICATED = 'AUTHENTICATED',
  LOGGING_OUT = 'LOGGING_OUT',
  ERROR = 'ERROR'
}