export enum ProviderLoadState {
  IDLE = 'IDLE',
  DETECTING_WALLETS = 'DETECTING_WALLETS',
  WALLET_DEDECTION_FAILED = 'WALLET_DEDECTION_FAILED',
  WAITING_WALLET_SELECTION = 'WAITING_WALLET_SELECTION',
  REQUESTED = 'REQUESTED',
  NOT_SUPPORTED = 'NOT_SUPPORTED',
  FAILED = 'FAILED',
  INITIALIZED = 'INITIALIZED',
}
