export enum AccountSignState {
  IDLE = 'IDLE',
  NOT_SIGNED = 'NOT_SIGNED',
  SIGN_INITIALIZED = 'SIGN_INITIALIZED',
  SIGN_REQUESTED = 'SIGN_REQUESTED',
  SIGN_REJECTED = 'SIGN_REJECTED',
  SIGN_TIMED_OUT = 'SIGN_TIMED_OUT',
  SIGN_FAILED = 'SIGN_FAILED',
  SIGNED = 'SIGNED',
}
