export enum WalletState {
  NOT_INITIALIZED = 'NOT_INITIALIZED',
  CHECKING_WALLET = 'CHECKING_WALLET',
  CHECKING_ACCOUNT = 'CHECKING_ACCOUNT',
  CHECKING_NETWORK = 'CHECKING_NETWORK',
  CHECKING_SIGN = 'CHECKING_SIGN',
  AUTHENTICATED = 'AUTHENTICATED',
}
