name: Check Version Label

on:
  workflow_call:
  workflow_dispatch:

env:
  VALID_LABELS: 'major,minor,patch'

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Version Label
        run: |
          # Extract labels from the pull request
          LABELS="${{ toJson(github.event.pull_request.labels.*.name) }}"

          # Print the labels for debugging
          echo "PR Labels: $LABELS"
          echo "Valid labels: $VALID_LABELS"

          # Convert the PR labels into a simple string, no quotes, to make comparison easier
          LABELS_ARRAY=$(echo "$LABELS" | jq -r '. | join(",")')

          # Split the labels and match against valid labels
          MATCHED_LABELS=$(echo "$LABELS_ARRAY" | tr ',' '\n' | grep -E "\b($(echo $VALID_LABELS | tr ',' '|'))\b")

          # Count the number of matched valid labels
          COUNT=$(echo "$MATCHED_LABELS" | wc -l)

          # If no valid label is found
          if [ "$COUNT" -eq 0 ]; then
            echo "Error: No valid version label found. Please add one of: $VALID_LABELS."
            exit 1
          # If more than one valid label is found
          elif [ "$COUNT" -gt 1 ]; then
            echo "Error: Multiple version labels found: $MATCHED_LABELS. Please ensure only one version label is used."
            exit 1
          fi

          # If exactly one valid label is found
          echo "Valid version label: $MATCHED_LABELS"
