name: Run Test and Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test
        env:
          VITE_ROUTER_USE_HASH: true
          VITE_WALLET_DISABLE_SIGN: false
          VITE_WALLET_SIGN_TIMEOUT_IN_SEC: 60
          VITE_WALLET_SLOW_DOWN_IN_MS: 1000
          VITE_POST_LOGIN_REDIRECT_PATH: '/user'

      - name: Build
        run: npm run build
