name: Run Test and Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test

      - name: Build
        run: npm run build
